export const MysqlErrorCode = {
  ER_DUP_ENTRY: 'ER_DUP_ENTRY',
  ER_NO_REFERENCED_ROW_2: 'ER_NO_REFERENCED_ROW_2',
  ER_BAD_NULL_ERROR: 'ER_BAD_NULL_ERROR',
  ER_DATA_TOO_LONG: 'ER_DATA_TOO_LONG',
  ER_NO_DEFAULT_FOR_FIELD: 'ER_NO_DEFAULT_FOR_FIELD',
  ER_TRUNCATED_WRONG_VALUE: 'ER_TRUNCATED_WRONG_VALUE',
  ER_PARSE_ERROR: 'ER_PARSE_ERROR',
  ER_BAD_FIELD_ERROR: 'ER_BAD_FIELD_ERROR',
  ER_NO_SUCH_TABLE: 'ER_NO_SUCH_TABLE',
  ER_ACCESS_DENIED_ERROR: 'ER_ACCESS_DENIED_ERROR',
};
